/**
 * DARK MATTER LAB — Pipeline & Workspace Constants
 * Master Blueprint specification definitions
 */

import { PhaseConfig, PhaseId, WorkspaceConfig, WorkspaceId } from './domain.ts';

export const PRODUCTION_PHASES: PhaseConfig[] = [
  {
    id: 'trend',
    label: 'TREND',
    order: 1,
    description: 'Cultural & algorithmic topic intelligence and velocity analysis',
    primaryWorkspace: 'trend',
  },
  {
    id: 'research',
    label: 'RESEARCH',
    order: 2,
    description: 'Deep factual research, entity verification & Fact Lock',
    primaryWorkspace: 'research',
  },
  {
    id: 'idea',
    label: 'IDEA',
    order: 3,
    description: 'Angle formulation, premise selection & creative hypothesis',
    primaryWorkspace: 'idea',
  },
  {
    id: 'story',
    label: 'STORY',
    order: 4,
    description: 'Narrative structure, tension curves & dramatic beats',
    primaryWorkspace: 'story',
  },
  {
    id: 'script',
    label: 'SCRIPT',
    order: 5,
    description: 'Full screenplay / narration drafting with voice locked',
    primaryWorkspace: 'script',
  },
  {
    id: 'scene_plan',
    label: 'SCENE PLAN',
    order: 6,
    description: 'Granular shot-by-shot visual pacing, camera & asset blueprint',
    primaryWorkspace: 'scene_plan',
  },
  {
    id: 'media',
    label: 'MEDIA / VOICE',
    order: 7,
    description: 'Voice synthesis, soundtrack stems, and generative visual clips',
    primaryWorkspace: 'audio',
  },
  {
    id: 'first_cut',
    label: 'AI FIRST CUT',
    order: 8,
    description: 'Automated rough cut assembly, sync alignment & timing pass',
    primaryWorkspace: 'first_cut',
  },
  {
    id: 'pro_editor',
    label: 'PRO EDITOR',
    order: 9,
    description: 'Non-linear multi-track editing, frame trims, sound design',
    primaryWorkspace: 'editor',
  },
  {
    id: 'thumbnail',
    label: 'THUMBNAIL',
    order: 10,
    description: 'High-CTR thumbnail packaging variants & visual hooks',
    primaryWorkspace: 'thumbnail',
  },
  {
    id: 'seo',
    label: 'SEO',
    order: 11,
    description: 'Algorithmic metadata, title variants & search indexing',
    primaryWorkspace: 'seo',
  },
  {
    id: 'youtube_studio',
    label: 'YOUTUBE STUDIO',
    order: 12,
    description: 'Channel staging, upload packaging & publishing governance',
    primaryWorkspace: 'youtube',
  },
  {
    id: 'analytics',
    label: 'ANALYTICS',
    order: 13,
    description: 'Retention curves, CTR feedback & future idea generation loop',
    primaryWorkspace: 'analytics',
  },
];

export const WORKSPACES: WorkspaceConfig[] = [
  // PRE-PRODUCTION
  {
    id: 'trend',
    name: 'Trend Intelligence',
    category: 'PRE-PRODUCTION',
    description: 'Algorithmic signal detection, cross-platform velocity tracking, and trend clustering.',
    targetPhase: 'trend',
    iconName: 'TrendingUp',
    inputsRequired: ['Niche Category', 'Search Keywords'],
    outputsProduced: ['Trend Dossier Artifact', 'Topic Momentum Score'],
  },
  {
    id: 'research',
    name: 'Research & Fact Lock',
    category: 'PRE-PRODUCTION',
    description: 'Deep source synthesis, verified claims ledger, and anti-hallucination fact anchors.',
    targetPhase: 'research',
    iconName: 'BookOpen',
    inputsRequired: ['Trend Dossier', 'Primary Citations'],
    outputsProduced: ['Fact Lock Dossier Artifact', 'Entity Knowledge Graph'],
  },
  {
    id: 'idea',
    name: 'Idea Generator',
    category: 'PRE-PRODUCTION',
    description: 'High-impact premise generator, curiosity gap analysis, and hook formulation.',
    targetPhase: 'idea',
    iconName: 'Lightbulb',
    inputsRequired: ['Fact Lock Dossier', 'Target Audience Persona'],
    outputsProduced: ['Premise Card', 'Hook Variants'],
  },
  {
    id: 'story',
    name: 'Story Engine',
    category: 'PRE-PRODUCTION',
    description: 'Three-act tension curves, pacing choreography, and emotional payoff architecture.',
    targetPhase: 'story',
    iconName: 'Compass',
    inputsRequired: ['Selected Premise Card', 'Pacing Style Profile'],
    outputsProduced: ['Story Beat Outline Artifact', 'Tension Curve Graph'],
  },
  {
    id: 'script',
    name: 'Script Engine',
    category: 'PRE-PRODUCTION',
    description: 'Screenplay drafting, dialog polish, and multi-format script import/export.',
    targetPhase: 'script',
    iconName: 'FileText',
    inputsRequired: ['Story Beat Outline', 'Tone & Persona Guidelines'],
    outputsProduced: ['Locked Screenplay Artifact', 'Word Count & Timing Budget'],
  },
  {
    id: 'scene_plan',
    name: 'Scene Planning',
    category: 'PRE-PRODUCTION',
    description: 'Shot-by-shot storyboard, camera angle orchestration, and asset manifest requirements.',
    targetPhase: 'scene_plan',
    iconName: 'Layers',
    inputsRequired: ['Locked Screenplay', 'Visual Style Guide'],
    outputsProduced: ['Scene Plan Sequence Artifact', 'Asset Manifest Requirements'],
  },

  // PRODUCTION
  {
    id: 'movie',
    name: 'Movie Intelligence',
    category: 'PRODUCTION',
    description: 'Feature film / web-series ingestion, proxy generation, shot detection, and breakdown.',
    targetPhase: 'scene_plan',
    iconName: 'Film',
    inputsRequired: ['Source Film Asset Reference', 'Audio Proxy'],
    outputsProduced: ['Movie Intelligence Dossier', 'Scene Breakdown Manifest'],
  },
  {
    id: 'audio',
    name: 'Audio Studio',
    category: 'PRODUCTION',
    description: 'Voice synthesis, emotional nuance parameters, background soundscapes, and audio stems.',
    targetPhase: 'media',
    iconName: 'Headphones',
    inputsRequired: ['Locked Script Narration', 'Voice Model Reference'],
    outputsProduced: ['Master Narration Stem', 'Music & SFX Asset References'],
  },
  {
    id: 'video',
    name: 'Video Generator',
    category: 'PRODUCTION',
    description: 'AI generative visual prompting, frame interpolation, and b-roll asset generation.',
    targetPhase: 'media',
    iconName: 'Clapperboard',
    inputsRequired: ['Scene Visual Prompts', 'Style Reference Assets'],
    outputsProduced: ['Generative Video Clip Asset References'],
  },

  // POST-PRODUCTION
  {
    id: 'first_cut',
    name: 'AI First Cut',
    category: 'POST-PRODUCTION',
    description: 'Automated rough cut synthesis, beat matching, audio sync, and sequence scaffolding.',
    targetPhase: 'first_cut',
    iconName: 'Scissors',
    inputsRequired: ['Audio Stems', 'Video Assets', 'Scene Plan Timing'],
    outputsProduced: ['First Cut Timeline Sequence Artifact'],
  },
  {
    id: 'editor',
    name: 'Professional Editor',
    category: 'POST-PRODUCTION',
    description: 'Full non-linear multi-track timeline, keyframing, color grading, and subtitle burning.',
    targetPhase: 'pro_editor',
    iconName: 'SlidersHorizontal',
    inputsRequired: ['First Cut Timeline Sequence', 'Full Asset References'],
    outputsProduced: ['Master Render EDL / Final Video Export Ref'],
  },
  {
    id: 'thumbnail',
    name: 'Thumbnail Studio',
    category: 'POST-PRODUCTION',
    description: 'Eye-tracking heatmap simulation, contrast analysis, and A/B thumbnail candidate packs.',
    targetPhase: 'thumbnail',
    iconName: 'Image',
    inputsRequired: ['Keyframe Video Frame References', 'Hook Title'],
    outputsProduced: ['Thumbnail Candidate Pack Artifact'],
  },

  // DISTRIBUTION
  {
    id: 'seo',
    name: 'SEO Studio',
    category: 'DISTRIBUTION',
    description: 'Algorithmic click-through optimization, semantic tag clusters, and search intent analysis.',
    targetPhase: 'seo',
    iconName: 'Search',
    inputsRequired: ['Video Topic', 'Narrative Summary'],
    outputsProduced: ['SEO Package Artifact (Titles, Tags, Description)'],
  },
  {
    id: 'youtube',
    name: 'YouTube Studio',
    category: 'DISTRIBUTION',
    description: 'Channel staging, upload metadata payload inspection, and scheduled release governance.',
    targetPhase: 'youtube_studio',
    iconName: 'Youtube',
    inputsRequired: ['Final Video Asset Ref', 'Thumbnail Pack', 'SEO Package'],
    outputsProduced: ['YouTube Upload Staging Payload', 'Publication Receipt'],
  },
  {
    id: 'analytics',
    name: 'Analytics Loop',
    category: 'DISTRIBUTION',
    description: 'Audience drop-off analytics, algorithmic feedback signals, and iterative premise loops.',
    targetPhase: 'analytics',
    iconName: 'BarChart3',
    inputsRequired: ['YouTube Analytics Feed', 'Audience Retention Data'],
    outputsProduced: ['Performance Retrospective Artifact', 'Future Premise Seeds'],
  },
];
